name: "Test"
on:
  pull_request:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
      
  e2e-test:
    runs-on: gnosis
    needs: build-test
    name: End to end tests
    steps:
      - uses: actions/checkout@v2
      - run: npx @dappnode/dappnodesdk@latest github-action test-end-to-end --errorLogsTimeout 120 --healthCheckUrl http://nethermind-xdai.dappnode:8545/ --network gnosis
        env:
          VALIDATOR_INDEX: ${{ secrets.GNOSIS_VALIDATOR_INDEX }}
